### ISSUE TITLE
Bridge IRC to Gitter

### ISSUE THREAD

**Issue by oxr463** [SharkBaitOS/mako-bot#1]
Contents of `matterbridge.toml` file:

```toml
[irc.myirc]
Nick="yournick" # <== change this
NickServNick="yournick" # <== change this if necessary (your nick registered with nickserv)
NickServPassword="yourpass" # <== change this (your pass with nickserv)
Server="irc.freenode.net:6697"
UseTLS=true
UseSASL=true
SkipTLSVerify=false
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
[gitter.mygitter]
#You can get your token by going to https://developer.gitter.im/docs/welcome and SIGN IN
Token="Yourtokenhere"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
#This improves the situation where a gitter user uploads a picture/file, just relay the link instead of the Markdown
ReplaceMessages=[["^\\[!\\[[^\\]]+\\]\\(https?:\\/\\/files\\.gitter\\.im\\/[^\\/]+\\/[^\\/]+\\/[^\\/]+\\/thumb\\/[^\\)]+\\)\\]\\(([^\\)]+)\\)$", "$1"], ["\\[[^\\]]+\\]\\((https:\\/\\/files\\.gitter\\.im\\/[^\\/]+\\/[^\\/]+\\/[^\\/]+\\/[^\\)]+)\\)$", "$1"]]
```

See: https://github.com/42wim/matterbridge/wiki/How-to-create-your-config
